# Generated by Django 3.2.8 on 2021-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikigai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ikigai',
            field=models.CharField(default='Default', max_length=35),
        ),
    ]
