# Generated by Django 3.2.8 on 2021-11-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikigai', '0002_client_ikigai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ikigai',
        ),
    ]
