# Generated by Django 3.2.8 on 2021-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('organizacao', models.FloatField(default=0)),
                ('tecnica', models.FloatField(default=0)),
                ('empreendedorismo', models.FloatField(default=0)),
                ('intraempreendedorismo', models.FloatField(default=0)),
                ('lideranca', models.FloatField(default=0)),
                ('geral', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
    ]
