# Generated by Django 3.2.8 on 2021-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atratividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comportamento',
            field=models.FloatField(default=0),
        ),
    ]
