# Generated by Django 3.2.8 on 2021-11-03 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atratividade', '0002_client_comportamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_data',
            field=models.DateField(default=datetime.date(2021, 11, 3)),
        ),
    ]
